version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8000:8000"

  tg-bot:
    build: ./tg-bot
    restart: unless-stopped
    env_file:
    - .env
    depends_on:
      - redis
