FROM python:3.13.2-slim
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY backend/ ./backend
COPY core/ ./core

# storage теперь монтируется извне, COPY больше не нужен
# Можно оставить папку на случай, если volume не подключат
RUN mkdir -p ./storage

RUN pip install -r backend/requirements.txt uvloop

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
