version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - BACKEND_ROUTE=http://backend:8000
    depends_on:
      - redis
    volumes:
      - ./storage:/app/storage
    ports:
      - "8888:8000"

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile.tg_bot
      args:
        INSTAGRAM_USERNAME: ${INSTAGRAM_USERNAME}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - BACKEND_ROUTE=http://backend:8000
    depends_on:
      - redis
      - backend
    volumes:
      - ./storage:/app/storage
